name: Build Repo Listing

on:
  release:
    types: [published, created, edited, deleted]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Listing
        uses: vrchat-community/package-list-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}